### PR TITLE
update to Rust 2018 edition

### PR DESCRIPTION
**Pull request by brayniac**
* changes to update to Rust 2018 edition
* add Brian Martin <brayniac@gmail.com> to authors in Cargo.toml

### CODE REVIEW

**Comment by jvns** [comment]
nice, thanks for doing this!

**Comment by brayniac** [comment]
@jvns - after this merges, will ask you to publish to crates.io. Adding myself to authors will allow me to publish updates in the future. Just getting one more fix in for repository and homepage urls in the cargo metadata

**Comment by jvns** [comment]
sounds good, I can do that.

**Comment by brayniac** [comment]
@jvns changes are merged. Please go ahead and publish to crates.io at your convenience and let me know. Thanks!

**Comment by jvns** [comment]
I ran `cargo owner --add github:rust-bpf:owners` and `cargo owner --add brayniac` and published the crate.

**Pull request merged**
