### PR TITLE
fix oh no bug (#51)

### PR DESCRIPTION
**Pull request by ethercflow**

### CODE REVIEW

**Comment by brayniac** [comment]
Awesome! Looking forward to getting this addressed. Overall the change looks OK, but we need to have a test for this in CI.

#50 has changes to make the opensnoop example run in bounded time. Two options: 1) I can cleanup #50 to get that running in CI, you will need to merge the change into your branch so that the example is run in CI for this PR before merge. 2) you can pull-in the changes to the opensnoop example and add it to the CI job in this PR

Let me know how you want to proceed.

**Comment by ethercflow** [comment]
@brayniac I choose the option 2), PTAL.

**Comment by brayniac** [comment]
Perfect. Nice seeing it test and pass in CI

**Comment by brayniac** [comment]
@ethercflow - thank you for your PR!

**Pull request merged**
